-- ====================================================================
-- SUPABASE MIGRATION: Schema Completo para Controle de Quadras & Cartões
-- ====================================================================

-- Habilitar extensões necessárias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABELA DE USUÁRIOS (PERFIS DO SISTEMA)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  usuario TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  senha_hash TEXT,
  permissao TEXT NOT NULL CHECK (permissao IN ('Administrador', 'Dirigente', 'Usuário comum')) DEFAULT 'Usuário comum',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE CIDADES
CREATE TABLE IF NOT EXISTS public.cidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABELA DE BAIRROS
CREATE TABLE IF NOT EXISTS public.bairros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES public.cidades(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABELA DE QUADRAS
CREATE TABLE IF NOT EXISTS public.quadras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES public.cidades(id) ON DELETE CASCADE,
  bairro_id BIGINT NOT NULL REFERENCES public.bairros(id) ON DELETE CASCADE,
  numero TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Não feita', 'Feita')) DEFAULT 'Não feita',
  concluida_em TIMESTAMPTZ,
  usuario_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  usuario_nome TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA DE CARTÕES DE TERRITÓRIO
CREATE TABLE IF NOT EXISTS public.cartoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descricao TEXT,
  cidade_id BIGINT REFERENCES public.cidades(id) ON DELETE CASCADE,
  bairro_id BIGINT REFERENCES public.bairros(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  usuario_nome TEXT,
  ultima_data_concluida TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CARTAO_QUADRAS (TABELA DE JUNÇÃO DE QUADRAS DO CARTÃO)
CREATE TABLE IF NOT EXISTS public.cartao_quadras (
  cartao_id BIGINT NOT NULL REFERENCES public.cartoes(id) ON DELETE CASCADE,
  quadra_id BIGINT NOT NULL REFERENCES public.quadras(id) ON DELETE CASCADE,
  PRIMARY KEY (cartao_id, quadra_id)
);

-- 7. CARTAO_DESIGNACOES (REGISTRO S-13 DE DESIGNAÇÃO DE TERRITÓRIOS)
CREATE TABLE IF NOT EXISTS public.cartao_designacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cartao_id BIGINT NOT NULL REFERENCES public.cartoes(id) ON DELETE CASCADE,
  dirigente_nome TEXT NOT NULL,
  data_designacao TEXT NOT NULL,
  data_conclusao TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. HISTÓRICO DE AÇÕES DE QUADRAS
CREATE TABLE IF NOT EXISTS public.historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quadra_id BIGINT REFERENCES public.quadras(id) ON DELETE CASCADE,
  cidade_nome TEXT NOT NULL,
  bairro_nome TEXT NOT NULL,
  numero TEXT NOT NULL,
  acao TEXT NOT NULL CHECK (acao IN ('Concluída', 'Resetada', 'Criada')),
  usuario_nome TEXT NOT NULL,
  data_hora TIMESTAMPTZ DEFAULT NOW()
);

-- 9. REGISTROS DE AUDITORIA DO SISTEMA
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  usuario_nome TEXT NOT NULL,
  acao TEXT NOT NULL,
  detalhes TEXT,
  ip TEXT,
  data_hora TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- ÍNDICES PARA ALTA PERFORMANCE
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_bairros_cidade_id ON public.bairros(cidade_id);
CREATE INDEX IF NOT EXISTS idx_quadras_cidade_id ON public.quadras(cidade_id);
CREATE INDEX IF NOT EXISTS idx_quadras_bairro_id ON public.quadras(bairro_id);
CREATE INDEX IF NOT EXISTS idx_quadras_status ON public.quadras(status);
CREATE INDEX IF NOT EXISTS idx_quadras_usuario_id ON public.quadras(usuario_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_cidade_id ON public.cartoes(cidade_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_bairro_id ON public.cartoes(bairro_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_usuario_id ON public.cartoes(usuario_id);
CREATE INDEX IF NOT EXISTS idx_historico_quadra_id ON public.historico(quadra_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_usuario_id ON public.audit_logs(usuario_id);

-- ====================================================================
-- POLÍTICAS DE SEGURANÇA (RLS)
-- ====================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bairros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quadras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartao_quadras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartao_designacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on users') THEN
    CREATE POLICY "Allow full access on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on cidades') THEN
    CREATE POLICY "Allow full access on cidades" ON public.cidades FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on bairros') THEN
    CREATE POLICY "Allow full access on bairros" ON public.bairros FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on quadras') THEN
    CREATE POLICY "Allow full access on quadras" ON public.quadras FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on cartoes') THEN
    CREATE POLICY "Allow full access on cartoes" ON public.cartoes FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on cartao_quadras') THEN
    CREATE POLICY "Allow full access on cartao_quadras" ON public.cartao_quadras FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on cartao_designacoes') THEN
    CREATE POLICY "Allow full access on cartao_designacoes" ON public.cartao_designacoes FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on historico') THEN
    CREATE POLICY "Allow full access on historico" ON public.historico FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow full access on audit_logs') THEN
    CREATE POLICY "Allow full access on audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
