-- ====================================================================
-- SUPABASE MIGRATION: Initial Schema for Quadras & Cartões Management
-- Generated: 2026-08-07
-- ====================================================================

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  usuario TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  senha_hash TEXT NOT NULL,
  permissao TEXT NOT NULL CHECK (permissao IN ('Administrador', 'Usuário comum')) DEFAULT 'Usuário comum',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CIDADES TABLE
CREATE TABLE IF NOT EXISTS public.cidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BAIRROS TABLE
CREATE TABLE IF NOT EXISTS public.bairros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES public.cidades(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. QUADRAS TABLE
CREATE TABLE IF NOT EXISTS public.quadras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES public.cidades(id) ON DELETE CASCADE,
  bairro_id BIGINT NOT NULL REFERENCES public.bairros(id) ON DELETE CASCADE,
  numero TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Não feita', 'Feita')) DEFAULT 'Não feita',
  concluida_em TIMESTAMPTZ,
  usuario_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  usuario_nome TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CARTOES TABLE
CREATE TABLE IF NOT EXISTS public.cartoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  descricao TEXT,
  cidade_id BIGINT REFERENCES public.cidades(id) ON DELETE CASCADE,
  bairro_id BIGINT REFERENCES public.bairros(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  usuario_nome TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CARTAO_QUADRAS (JUNCTION TABLE)
CREATE TABLE IF NOT EXISTS public.cartao_quadras (
  cartao_id BIGINT NOT NULL REFERENCES public.cartoes(id) ON DELETE CASCADE,
  quadra_id BIGINT NOT NULL REFERENCES public.quadras(id) ON DELETE CASCADE,
  PRIMARY KEY (cartao_id, quadra_id)
);

-- 7. HISTORICO TABLE
CREATE TABLE IF NOT EXISTS public.historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quadra_id BIGINT REFERENCES public.quadras(id) ON DELETE CASCADE,
  cidade_nome TEXT NOT NULL,
  bairro_nome TEXT NOT NULL,
  numero TEXT NOT NULL,
  acao TEXT NOT NULL CHECK (acao IN ('Concluída', 'Resetada', 'Criada')),
  usuario_nome TEXT NOT NULL,
  data_hora TIMESTAMPTZ DEFAULT NOW()
);

-- 8. AUDIT_LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  usuario_nome TEXT NOT NULL,
  acao TEXT NOT NULL,
  detalhes TEXT,
  ip TEXT,
  data_hora TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- INDEXES FOR OPTIMAL QUERY PERFORMANCE
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_bairros_cidade_id ON public.bairros(cidade_id);
CREATE INDEX IF NOT EXISTS idx_quadras_cidade_id ON public.quadras(cidade_id);
CREATE INDEX IF NOT EXISTS idx_quadras_bairro_id ON public.quadras(bairro_id);
CREATE INDEX IF NOT EXISTS idx_quadras_status ON public.quadras(status);
CREATE INDEX IF NOT EXISTS idx_quadras_usuario_id ON public.quadras(usuario_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_cidade_id ON public.cartoes(cidade_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_bairro_id ON public.cartoes(bairro_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_usuario_id ON public.cartoes(usuario_id);
CREATE INDEX IF NOT EXISTS idx_historico_quadra_id ON public.historico(quadra_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_usuario_id ON public.audit_logs(usuario_id);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bairros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quadras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartao_quadras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Create permissive policies for anon and authenticated access
DO $$
BEGIN
  -- users policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on users') THEN
    CREATE POLICY "Enable full access for anon/auth on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- cidades policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on cidades') THEN
    CREATE POLICY "Enable full access for anon/auth on cidades" ON public.cidades FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- bairros policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on bairros') THEN
    CREATE POLICY "Enable full access for anon/auth on bairros" ON public.bairros FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- quadras policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on quadras') THEN
    CREATE POLICY "Enable full access for anon/auth on quadras" ON public.quadras FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- cartoes policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on cartoes') THEN
    CREATE POLICY "Enable full access for anon/auth on cartoes" ON public.cartoes FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- cartao_quadras policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on cartao_quadras') THEN
    CREATE POLICY "Enable full access for anon/auth on cartao_quadras" ON public.cartao_quadras FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- historico policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on historico') THEN
    CREATE POLICY "Enable full access for anon/auth on historico" ON public.historico FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- audit_logs policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable full access for anon/auth on audit_logs') THEN
    CREATE POLICY "Enable full access for anon/auth on audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
